### ISSUE TITLE
Business Central Showcase -> OSE: Steps to fix permissions?

### ISSUE THREAD

**Issue by snimmagadda1** [jboss-dockerfiles/business-central#3]
I tried to deploy the showcase workbench image out of the box to OSE and am seeing some permission errors with log files not existing or the jboss user doesn't have permission to startup the server... (sort've expected w/ OSE)... Here's the exact output: 

```

Failed to read or configure the org.jboss.logmanager.LogManager
--
  | java.lang.IllegalArgumentException: Failed to instantiate class "org.jboss.logmanager.handlers.PeriodicRotatingFileHandler" for handler "FILE"
  | at org.jboss.logmanager.config.AbstractPropertyConfiguration$ConstructAction.validate(AbstractPropertyConfiguration.java:117)
  | at org.jboss.logmanager.config.LogContextConfigurationImpl.doPrepare(LogContextConfigurationImpl.java:336)
  | at org.jboss.logmanager.config.LogContextConfigurationImpl.prepare(LogContextConfigurationImpl.java:289)
  | at org.jboss.logmanager.config.LogContextConfigurationImpl.commit(LogContextConfigurationImpl.java:298)
  | at org.jboss.logmanager.PropertyConfigurator.configure(PropertyConfigurator.java:546)
  | at org.jboss.logmanager.PropertyConfigurator.configure(PropertyConfigurator.java:97)
  | at org.jboss.logmanager.LogManager.readConfiguration(LogManager.java:170)
  | at org.jboss.logmanager.LogManager.readConfiguration(LogManager.java:132)
  | at java.util.logging.LogManager$3.run(LogManager.java:399)
  | at java.util.logging.LogManager$3.run(LogManager.java:396)
  | at java.security.AccessController.doPrivileged(Native Method)
  | at java.util.logging.LogManager.readPrimordialConfiguration(LogManager.java:396)
  | at java.util.logging.LogManager.access$800(LogManager.java:145)
  | at java.util.logging.LogManager$2.run(LogManager.java:345)
  | at java.security.AccessController.doPrivileged(Native Method)
  | at java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:338)
  | at java.util.logging.LogManager.getLogManager(LogManager.java:378)
  | at org.jboss.modules.Main.main(Main.java:523)
  | Caused by: java.lang.reflect.InvocationTargetException
  | at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  | at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  | at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  | at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  | at org.jboss.logmanager.config.AbstractPropertyConfiguration$ConstructAction.validate(AbstractPropertyConfiguration.java:115)
  | ... 17 more
  | Caused by: java.io.FileNotFoundException: /opt/jboss/wildfly/standalone/log/server.log (Permission denied)
  | at java.io.FileOutputStream.open0(Native Method)
  | at java.io.FileOutputStream.open(FileOutputStream.java:270)
  | at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
  | at org.jboss.logmanager.handlers.FileHandler.setFile(FileHandler.java:151)
  | at org.jboss.logmanager.handlers.PeriodicRotatingFileHandler.setFile(PeriodicRotatingFileHandler.java:104)
  | at org.jboss.logmanager.handlers.FileHandler.setFileName(FileHandler.java:189)
  | at org.jboss.logmanager.handlers.FileHandler.<init>(FileHandler.java:119)
  | at org.jboss.logmanager.handlers.PeriodicRotatingFileHandler.<init>(PeriodicRotatingFileHandler.java:72)
  | ... 22 more
  | java.util.concurrent.ExecutionException: JBTHR00005: Operation failed
  | at org.jboss.threads.AsyncFutureTask.get(AsyncFutureTask.java:253)
  | at org.jboss.as.server.Main.main(Main.java:109)
  | at org.jboss.modules.Module.run(Module.java:352)
  | at org.jboss.modules.Module.run(Module.java:320)
  | at org.jboss.modules.Main.main(Main.java:593)
  | Caused by: org.jboss.msc.service.StartException in service jboss.as: Failed to start service
  | at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1728)
  | at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1556)
  | at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
  | at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
  | at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
  | at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378)
  | at java.lang.Thread.run(Thread.java:748)
  | Caused by: java.lang.IllegalStateException: WFLYDR0006: Directory /opt/jboss/wildfly/standalone/data/content is not writable
  | at org.jboss.as.repository.ContentRepositoryImpl.checkDirectory(ContentRepositoryImpl.java:101)
  | at org.jboss.as.repository.ContentRepositoryImpl.<init>(ContentRepositoryImpl.java:83)
  | at org.jboss.as.repository.ContentRepository$Factory.addService(ContentRepository.java:188)
  | at org.jboss.as.server.ApplicationServerService.start(ApplicationServerService.java:148)
  | at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1736)
  | at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1698)
  | ... 6 more


```
Any ideas on what changes to make permission wise in the Dockerfile for the server to run? I've been able to successfully run the drools workbench showcase image [here](https://github.com/jboss-dockerfiles/drools) in OSE, though it is 7.17 and we were hoping to upgrade. Here's the dockerfile being used:

```
###############################################################################################
# Dockerfile that provides the image for JBoss Business-Central Workbench 7.23.0.Final Showcase
###############################################################################################

####### BASE ############
FROM jboss/business-central-workbench:7.23.0.Final

####### MAINTAINER ############
MAINTAINER "Michael Biarnes Kiefer" "mbiarnes@redhat.com"

####### ENVIRONMENT ############
# Use demo and examples by default in this showcase image (internet connection required).
ENV KIE_SERVER_PROFILE standalone
ENV JAVA_OPTS -Xms256m -Xmx2048m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=512m -Djava.net.preferIPv4Stack=true -Dfile.encoding=UTF-8

####### jBPM Workbench CUSTOM CONFIGURATION ############
ADD etc/application-users.properties $JBOSS_HOME/standalone/configuration/application-users.properties
ADD etc/application-roles.properties $JBOSS_HOME/standalone/configuration/application-roles.properties
ADD etc/jbpm-custom.cli $JBOSS_HOME/bin/jbpm-custom.cli

# Added files are chowned to root user, change it to the jboss one.
USER root
RUN chown jboss:jboss $JBOSS_HOME/standalone/configuration/application-users.properties && \
chown jboss:jboss $JBOSS_HOME/standalone/configuration/application-roles.properties

# Switchback to jboss user
USER jboss
RUN $JBOSS_HOME/bin/jboss-cli.sh --file=$JBOSS_HOME/bin/jbpm-custom.cli && \
rm -rf $JBOSS_HOME/standalone/configuration/standalone_xml_history/current

####### RUNNING JBPM-WB ############
WORKDIR $JBOSS_HOME/bin/
CMD ["./start_business-central-wb.sh"]
```

**Comment by snimmagadda1** [comment]
So as a lazy quick solution I added this line to the Dockerfile

```
RUN chmod -R 766 $JBOSS_HOME/
```

And no longer get Wildfly issues but now OSE doesn't like the following 
```
CMD ["./start_business-central-wb.sh"]
```

and gives the output 

```

bash: ./start_business-central-wb.sh: Permission denied
--


```

Any ideas? I tried making it executable, changing the owner, etc...

```
RUN chmod +x start_business-central-wb.sh
```

**Comment by snimmagadda1** [comment]
Aight more permission fixes got me to this error... seems like it can't execute standalone.sh:
```

  | Running business-central workbench on JBoss Wildfly...
-- | --
  | ./start_business-central-wb.sh: line 5: /opt/jboss/wildfly/bin/standalone.sh: Permission denied
  | ./start_business-central-wb.sh: line 5: exec: /opt/jboss/wildfly/bin/standalone.sh: cannot execute: Permission denied


``` 

specifically the line beginning with exec...

**Comment by j-chao** [comment]
OpenShift requires that any "directories and files that may be written to by processes in the image should be owned by the root group and be read/writable by that group. Files to be executed should also have group execute permissions." 
(https://docs.openshift.com/container-platform/3.9/creating_images/guidelines.html)

I believe you are getting a permissions error because standalone.sh and start_business-central-wb.sh are only executable by the jboss group. These files need to have root group execute permissions.
